# Generated by Django 2.2 on 2019-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juzgados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juzgado',
            name='actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juzgado',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
