# Generated by Django 2.2 on 2019-06-19 05:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juzgados', '0003_auto_20190430_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateField(default=datetime.datetime(2019, 6, 19, 2, 13, 13, 414526))),
                ('juzgado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='juzgados.Juzgado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
