# Generated by Django 2.2 on 2019-06-19 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juzgados', '0005_auto_20190619_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegado',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 2, 14, 31, 807567)),
        ),
    ]
