# Generated by Django 2.2 on 2019-04-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='demo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='nota',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='separador',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='tipo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
