# Generated by Django 2.2 on 2019-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0002_auto_20190430_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='nota',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='tipo',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=50),
        ),
    ]
