# Generated by Django 2.2 on 2019-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0003_auto_20190430_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='tipo',
            field=models.CharField(choices=[('conFoja', 'Con Foja'), ('sinFoja', 'Sin Foja'), ('L', 'Large')], max_length=20),
        ),
    ]
