# Generated by Django 2.2 on 2019-04-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0006_auto_20190430_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='tipos_de_caratulas',
        ),
        migrations.AddField(
            model_name='tipocaratula',
            name='nombre_tipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
