# Generated by Django 2.2 on 2019-04-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0007_auto_20190430_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='tipos_de_caratulas',
            field=models.ManyToManyField(related_name='tipos_de_caratulas', to='extractor.TipoCaratula'),
        ),
    ]
