# Generated by Django 2.2 on 2019-04-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0008_plantilla_tipos_de_caratulas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocaratula',
            old_name='nombre_tipo',
            new_name='nombre',
        ),
    ]
