# Generated by Django 2.2 on 2019-04-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0009_auto_20190430_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='nota',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tipocaratula',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
