# Generated by Django 2.2 on 2019-04-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0011_auto_20190430_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocaratula',
            name='patron',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
