# Generated by Django 2.2 on 2019-04-30 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0012_auto_20190430_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocaratula',
            name='caratula',
        ),
    ]
