# Generated by Django 2.2 on 2019-05-03 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0013_remove_tipocaratula_caratula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='tipos_de_caratulas',
        ),
        migrations.AddField(
            model_name='plantilla',
            name='tipos_de_caratulas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='extractor.TipoCaratula'),
        ),
    ]
