# Generated by Django 2.2 on 2019-05-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0014_auto_20190503_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='cargar_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despacho',
            name='cargar_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
