# Generated by Django 2.2 on 2019-05-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0015_auto_20190504_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='cargar_desde',
            field=models.DateField(blank=True, null=True),
        ),
    ]
