# Generated by Django 2.2 on 2019-05-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0016_auto_20190504_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='cargar_hasta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
