# Generated by Django 2.2 on 2019-04-28 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='subscriptores',
            field=models.ManyToManyField(related_name='subcripciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
