# Generated by Django 2.2 on 2019-04-28 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_expediente_subscriptores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='subscriptores',
            field=models.ManyToManyField(related_name='subscriptores', to=settings.AUTH_USER_MODEL),
        ),
    ]
