# Generated by Django 2.2 on 2019-04-28 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_auto_20190428_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='autor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='subscriptores',
            field=models.ManyToManyField(null=True, related_name='subscriptores', to=settings.AUTH_USER_MODEL),
        ),
    ]
