# Generated by Django 2.2 on 2019-04-30 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_auto_20190430_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='subscriptores',
            field=models.ManyToManyField(related_name='subscriptores', to=settings.AUTH_USER_MODEL),
        ),
    ]
