# Generated by Django 2.2 on 2019-05-06 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0008_auto_20190506_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacion',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
