# Generated by Django 2.2 on 2019-05-06 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0010_auto_20190506_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='subscriptores',
            field=models.ManyToManyField(blank=True, related_name='subscriptores', to=settings.AUTH_USER_MODEL),
        ),
    ]
