# Generated by Django 2.2 on 2019-05-19 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0011_auto_20190506_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActualizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='actualizacion',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expedientes.TipoActualizacion'),
        ),
    ]
