# Generated by Django 2.2 on 2019-05-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0012_auto_20190518_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacion',
            name='tipo',
            field=models.CharField(choices=[('M', 'Movimiento'), ('P', 'Proveído/Actuación'), ('E', 'Escritos/Cargos')], max_length=1, null=True),
        ),
    ]
