# Generated by Django 2.2 on 2019-05-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0013_auto_20190518_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoActualizacion',
        ),
    ]
