# Generated by Django 2.2 on 2019-05-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0014_delete_tipoactualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualizacion',
            name='tipo',
            field=models.CharField(choices=[('M', 'Movimiento'), ('P', 'Proveído/Actuación'), ('E', 'Escritos/Cargos')], default='M', max_length=1, null=True),
        ),
    ]
