# Generated by Django 2.2 on 2019-05-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0015_auto_20190518_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='demandado',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
