# Generated by Django 2.2 on 2019-05-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0016_auto_20190522_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='demandado',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
