# Generated by Django 2.2 on 2019-05-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0018_auto_20190522_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='fecha_publicado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
