# Generated by Django 2.2 on 2019-05-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0021_auto_20190523_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='numero',
            field=models.CharField(max_length=20),
        ),
    ]
